### ISSUE TITLE
webport issue

### ISSUE THREAD

**Issue by frank3427** [sisaenkov/docker#3]
when I run you docker run and the open the webport 8080, 
I am getting a not found.

what should be displayed:

**Comment by sisaenkov** [comment]
> when I run you docker run and the open the webport 8080,
> I am getting a not found.
> 
> what should be displayed:

Did you create videoserverd.config?
What does logs show (docker logs -f ivideon-server) ?

Test run with config example from README.md is ok:
`docker run -d --name=ivideon-server --restart=always -e EMAIL=example@gmail.com -e SERVER_NAME=Test -v ./conf:/config -p 8080:8080 sisaenkov/ivideon-server`

$ netstat -ntul | grep 8080
`tcp6       0      0 :::8080                 :::*                    LISTEN`

$ docker ps
`08a22c3c104b        sisaenkov/ivideon-server   "/bin/bash -c '/entr…"   4 minutes ago       Up 4 minutes        0.0.0.0:8080->8080/tcp   ivideon-server`

**Comment by frank3427** [comment]
```ecc@azure-edge4:~$ netstat -ntul | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN     
ecc@azure-edge4:~$ docker logs -f ivideon-server
Registering server in Ivideon cloud...
I [2019-04-20 03:17:20.056][t:13](utils):<utils::openssl> CA bundles have been successfully loaded: /opt/ivideon/ivideon-server/cacert.pem
D [2019-04-20 03:17:20.717][t:13](utils):<ivideon_rest> POST request: url=`https://api.ivideon.com/public/roster', status=200, data=`login=frank%40xxxxx.com&name=loft&extra=%7B%22app_version%22%3A%223.7.0.2642%22%2C%22build_type%22%3A%22linux_server%22%7D%0A', result=`{"response":{"email":"frank@xxx.com","password":"xxxxs","id":"200-7xxxxx","name":"loft","uin":200001325038},"success":true}'
 * Restarting Video server videoserver
   ...done.
```

videoserverd.config
is your example but no secondary archives and jut one camera

**Comment by sisaenkov** [comment]
The best way to create a configuration file is to setup Ivideon Server application through a graphical interface on any Desktop Windows or Linux system. Then copy obtained config file from ~/.IvideonServer/videoserverd.config or C:\Users\<USER>\AppData\Local\Ivideon\IvideonServer\videoserverd.config to /config volume location.
